schema_version: 1

context:
  name: azure-mgmt-iotcentral
  version: 10.0.0b2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-iotcentral-${{ version }}.zip
  sha256: 0366753a58884951de5554872453b0b3281a0147fd2dc97cec048a589f08c6e4

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - msrest >=0.7.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing-extensions >=4.3.0

tests:
  - python:
      imports:
        - azure.mgmt.iotcentral
        - azure.mgmt.iotcentral.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Iotcentral Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
